FROM flyway/flyway:7.7.3-alpine

# COPY ./migrations/sql /flyway/sql/

#CMD ["flyway -url=jdbc:postgresql://postgres-master:5432/wallet -user=test_user -password=testuser1234  -connectRetries=60 -schemas=wallet migrate"]